apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "element.fullname" . }}
  labels:
    {{- include "element.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "element.fullname" . }}
            port:
              number: {{ .Values.service.port }}
