apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
type: Opaque
data:
  signing.key: ZWQyNTUxOSBhX3lpWkkgRXJzekRlUnB3ZFRGZGMvZlp5eGVUOHlxbnpsQURvbC9JQ3IvL3MrWi9icwo=
